# Generated by Django 4.0.3 on 2022-04-03 03:39
# This file was generate from the 2 "makemigrations", we rename the file

from django.db import migrations


class Migration(migrations.Migration):

    # This migration is dependent of the "0001_initial" migration in the store app
    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
    ]
